//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2SLogistics.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T2SLogistics.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I confirm closing the order?.
        /// </summary>
        internal static string CustomerOrderDetail_ConfirmationClosingTheOrder {
            get {
                return ResourceManager.GetString("CustomerOrderDetail_ConfirmationClosingTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        internal static string CustomerOrderDetail_ProcessCompleted {
            get {
                return ResourceManager.GetString("CustomerOrderDetail_ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved data.
        /// </summary>
        internal static string CustomerOrderDetail_SavedData {
            get {
                return ResourceManager.GetString("CustomerOrderDetail_SavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close order.
        /// </summary>
        internal static string CustomerOrderDetailPage_CloseOrder {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_CloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerOrderDetailPage_Customer {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string CustomerOrderDetailPage_Date {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Reading.
        /// </summary>
        internal static string CustomerOrderDetailPage_FinishReading {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_FinishReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string CustomerOrderDetailPage_Incomplete {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Box.
        /// </summary>
        internal static string CustomerOrderDetailPage_NewBox {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_NewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string CustomerOrderDetailPage_OrderDetails {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        internal static string CustomerOrderDetailPage_OrderNumber {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Products.
        /// </summary>
        internal static string CustomerOrderDetailPage_OrderProducts {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_OrderProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Boxes.
        /// </summary>
        internal static string CustomerOrderDetailPage_ProcessedBoxes {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_ProcessedBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CustomerOrderDetailPage_Status {
            get {
                return ResourceManager.GetString("CustomerOrderDetailPage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks.
        /// </summary>
        internal static string HomePage_Breaks {
            get {
                return ResourceManager.GetString("HomePage_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceramics management.
        /// </summary>
        internal static string HomePage_Ceramicsmanagement {
            get {
                return ResourceManager.GetString("HomePage_Ceramicsmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition.
        /// </summary>
        internal static string HomePage_Expedition {
            get {
                return ResourceManager.GetString("HomePage_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Production.
        /// </summary>
        internal static string HomePage_InsertProduction {
            get {
                return ResourceManager.GetString("HomePage_InsertProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string HomePage_Inventory {
            get {
                return ResourceManager.GetString("HomePage_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch finished products.
        /// </summary>
        internal static string HomePage_LaunchFinishedProducts {
            get {
                return ResourceManager.GetString("HomePage_LaunchFinishedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string HomePage_Operator {
            get {
                return ResourceManager.GetString("HomePage_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string HomePage_Orders {
            get {
                return ResourceManager.GetString("HomePage_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Separation.
        /// </summary>
        internal static string HomePage_OrderSeparation {
            get {
                return ResourceManager.GetString("HomePage_OrderSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string HomePage_Point {
            get {
                return ResourceManager.GetString("HomePage_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Record.
        /// </summary>
        internal static string HomePage_PointRecord {
            get {
                return ResourceManager.GetString("HomePage_PointRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Orders.
        /// </summary>
        internal static string HomePage_ProductionOrders {
            get {
                return ResourceManager.GetString("HomePage_ProductionOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production system.
        /// </summary>
        internal static string HomePage_ProductionSystem {
            get {
                return ResourceManager.GetString("HomePage_ProductionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register entry and exit.
        /// </summary>
        internal static string HomePage_RegisterEntryAndExit {
            get {
                return ResourceManager.GetString("HomePage_RegisterEntryAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View production orders.
        /// </summary>
        internal static string HomePage_ViewProductionOrders {
            get {
                return ResourceManager.GetString("HomePage_ViewProductionOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Control.
        /// </summary>
        internal static string InsertProductionPage_AttendanceControl {
            get {
                return ResourceManager.GetString("InsertProductionPage_AttendanceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string InsertProductionPage_EmployeeID {
            get {
                return ResourceManager.GetString("InsertProductionPage_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string InsertProductionPage_Enter {
            get {
                return ResourceManager.GetString("InsertProductionPage_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your ID.
        /// </summary>
        internal static string InsertProductionPage_EnterUourID {
            get {
                return ResourceManager.GetString("InsertProductionPage_EnterUourID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string InsertProductionPage_Exit {
            get {
                return ResourceManager.GetString("InsertProductionPage_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify employee.
        /// </summary>
        internal static string InsertProductionPage_IdentifyEmployee {
            get {
                return ResourceManager.GetString("InsertProductionPage_IdentifyEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation *.
        /// </summary>
        internal static string InsertProductionPage_Operation {
            get {
                return ResourceManager.GetString("InsertProductionPage_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Record.
        /// </summary>
        internal static string InsertProductionPage_PointRecord {
            get {
                return ResourceManager.GetString("InsertProductionPage_PointRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string InsertProductionPage_Production {
            get {
                return ResourceManager.GetString("InsertProductionPage_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Produced.
        /// </summary>
        internal static string InsertProductionPage_QuantityProduced {
            get {
                return ResourceManager.GetString("InsertProductionPage_QuantityProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Production.
        /// </summary>
        internal static string InsertProductionPage_RegisterProduction {
            get {
                return ResourceManager.GetString("InsertProductionPage_RegisterProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Order.
        /// </summary>
        internal static string InsertProductionPage_SelectedOrder {
            get {
                return ResourceManager.GetString("InsertProductionPage_SelectedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Quantity.
        /// </summary>
        internal static string InsertProductQuantityPopup_InsertQuantity {
            get {
                return ResourceManager.GetString("InsertProductQuantityPopup_InsertQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Breaks.
        /// </summary>
        internal static string InsertProductQuantityPopup_QtyBreaks {
            get {
                return ResourceManager.GetString("InsertProductQuantityPopup_QtyBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Produced.
        /// </summary>
        internal static string InsertProductQuantityPopup_QtyProduced {
            get {
                return ResourceManager.GetString("InsertProductQuantityPopup_QtyProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save production entry.
        /// </summary>
        internal static string InsertProductQuantityPopup_SaveProductionEntry {
            get {
                return ResourceManager.GetString("InsertProductQuantityPopup_SaveProductionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        internal static string LoginPage_CreateNewAccount {
            get {
                return ResourceManager.GetString("LoginPage_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string LoginPage_EnterYourEmail {
            get {
                return ResourceManager.GetString("LoginPage_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string LoginPage_EnterYourPassword {
            get {
                return ResourceManager.GetString("LoginPage_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        internal static string LoginPage_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginPage_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to continue.
        /// </summary>
        internal static string LoginPage_LoginToContinue {
            get {
                return ResourceManager.GetString("LoginPage_LoginToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LoginPage_RememberMe {
            get {
                return ResourceManager.GetString("LoginPage_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginPage_Username {
            get {
                return ResourceManager.GetString("LoginPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoginPage_Welcome {
            get {
                return ResourceManager.GetString("LoginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available products.
        /// </summary>
        internal static string OrderDetailsPage_AvailableProducts {
            get {
                return ResourceManager.GetString("OrderDetailsPage_AvailableProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string OrderReadingPage_Articles {
            get {
                return ResourceManager.GetString("OrderReadingPage_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Reading.
        /// </summary>
        internal static string OrderReadingPage_BarcodeReading {
            get {
                return ResourceManager.GetString("OrderReadingPage_BarcodeReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OrderReadingPage_Cancel {
            get {
                return ResourceManager.GetString("OrderReadingPage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string OrderReadingPage_Clear {
            get {
                return ResourceManager.GetString("OrderReadingPage_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string OrderReadingPage_Manual {
            get {
                return ResourceManager.GetString("OrderReadingPage_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Progress.
        /// </summary>
        internal static string OrderReadingPage_ReadingProgress {
            get {
                return ResourceManager.GetString("OrderReadingPage_ReadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string OrderReadingPage_SaveReading {
            get {
                return ResourceManager.GetString("OrderReadingPage_SaveReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan or enter the code....
        /// </summary>
        internal static string OrderReadingPage_ScanOrEnterTheCode {
            get {
                return ResourceManager.GetString("OrderReadingPage_ScanOrEnterTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected article!.
        /// </summary>
        internal static string OrderReadingPage_UnExpectedArticle {
            get {
                return ResourceManager.GetString("OrderReadingPage_UnExpectedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string OrderSeprationDetailPage_Back {
            get {
                return ResourceManager.GetString("OrderSeprationDetailPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string OrderSeprationDetailPage_Complete {
            get {
                return ResourceManager.GetString("OrderSeprationDetailPage_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string OrderSeprationDetailPage_Confirm {
            get {
                return ResourceManager.GetString("OrderSeprationDetailPage_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing: .
        /// </summary>
        internal static string OrderSeprationDetailPage_Missing {
            get {
                return ResourceManager.GetString("OrderSeprationDetailPage_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate Qtt.
        /// </summary>
        internal static string OrderSeprationDetailPage_SeparateQuantity {
            get {
                return ResourceManager.GetString("OrderSeprationDetailPage_SeparateQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Separation.
        /// </summary>
        internal static string OrderSeprationPage_StartSeparation {
            get {
                return ResourceManager.GetString("OrderSeprationPage_StartSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        internal static string ResetNewPasswordPage_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetNewPasswordPage_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ResetNewPasswordPage_ConfirmPasswordTitle {
            get {
                return ResourceManager.GetString("ResetNewPasswordPage_ConfirmPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        internal static string ResetNewPasswordPage_NewPassword {
            get {
                return ResourceManager.GetString("ResetNewPasswordPage_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ResetNewPasswordPage_NewPasswordTitle {
            get {
                return ResourceManager.GetString("ResetNewPasswordPage_NewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetNewPasswordPage_Title {
            get {
                return ResourceManager.GetString("ResetNewPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack.
        /// </summary>
        internal static string String_Lack {
            get {
                return ResourceManager.GetString("String_Lack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string String_OR {
            get {
                return ResourceManager.GetString("String_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string String_Orders {
            get {
                return ResourceManager.GetString("String_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string String_Read {
            get {
                return ResourceManager.GetString("String_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string StringContinue {
            get {
                return ResourceManager.GetString("StringContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the .
        /// </summary>
        internal static string ViewOrdersPage_ChooseThe {
            get {
                return ResourceManager.GetString("ViewOrdersPage_ChooseThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the PRODUCT Order.
        /// </summary>
        internal static string ViewOrdersPage_ChooseTheProductOrder {
            get {
                return ResourceManager.GetString("ViewOrdersPage_ChooseTheProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        internal static string ViewOrdersPage_OpenOrders {
            get {
                return ResourceManager.GetString("ViewOrdersPage_OpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Order.
        /// </summary>
        internal static string ViewOrdersPage_Order {
            get {
                return ResourceManager.GetString("ViewOrdersPage_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PRODUCT.
        /// </summary>
        internal static string ViewOrdersPage_Product {
            get {
                return ResourceManager.GetString("ViewOrdersPage_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for products by code or name....
        /// </summary>
        internal static string ViewOrdersPage_SearchProductPlaceholder {
            get {
                return ResourceManager.GetString("ViewOrdersPage_SearchProductPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Production.
        /// </summary>
        internal static string ViewOrdersPage_StartProduction {
            get {
                return ResourceManager.GetString("ViewOrdersPage_StartProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  that you will work on:.
        /// </summary>
        internal static string ViewOrdersPage_Workon {
            get {
                return ResourceManager.GetString("ViewOrdersPage_Workon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string ViewProductOperationPage_Available {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprocess.
        /// </summary>
        internal static string ViewProductOperationPage_Inprocess {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_Inprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OPERATION.
        /// </summary>
        internal static string ViewProductOperationPage_Operation {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search for operations....
        /// </summary>
        internal static string ViewProductOperationPage_SearchForOperation {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_SearchForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Product: .
        /// </summary>
        internal static string ViewProductOperationPage_SelectedProduct {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_SelectedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to perform:.
        /// </summary>
        internal static string ViewProductOperationPage_ToPerform {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_ToPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ViewProductOperationPage_Total {
            get {
                return ResourceManager.GetString("ViewProductOperationPage_Total", resourceCulture);
            }
        }
    }
}
